### PR TITLE
fix removing Committed

### LINKED ISSUE #22: Datasets don't seem to be cleaned up properly on image removal.
When removing an image, the associated snapshot is removed but the zfs filesystem is left behind:

```
% sudo zfs list -r dataz/k8s/containerd -t all
NAME                   USED  AVAIL  REFER  MOUNTPOINT
dataz/k8s/containerd   184K  3.41T   184K  /dataz/k8s/containerd

% sudo CONTAINERD_SNAPSHOTTER=zfs ctr images pull docker.io/library/busybox:latest
docker.io/library/busybox:latest:                                                 resolved       
...snip...
unpacking linux/amd64 sha256:4b6ad3a68d34da29bf7c8ccb5d355ba8b4babcad1f99798204e7abb43e54ee3d...
done

% sudo zfs list -r dataz/k8s/containerd -t all
NAME                              USED  AVAIL  REFER  MOUNTPOINT
dataz/k8s/containerd             2.03M  3.41T   960K  /dataz/k8s/containerd
dataz/k8s/containerd/5           1.09M  3.41T  1.09M  legacy
dataz/k8s/containerd/5@snapshot     0B      -  1.09M  -

% sudo CONTAINERD_SNAPSHOTTER=zfs ctr images rm docker.io/library/busybox:latest
docker.io/library/busybox:latest

% sudo zfs list -r dataz/k8s/containerd -t all
NAME                     USED  AVAIL  REFER  MOUNTPOINT
dataz/k8s/containerd    1.27M  3.41T   184K  /dataz/k8s/containerd
dataz/k8s/containerd/5  1.09M  3.41T  1.09M  legacy
```

It seems to work for removing snapshots and also removing the read/write images created during container execution. It just seems to leave behind the base image filesystem.

Please let me know if there's any more information I can provide.

### PR DESCRIPTION
**Pull request by AkihiroSuda**
when removing Committed, the ZFS dataset `foopool/foofs/42@snapshot` was
removed but `foopool/foofs/42` was not removed.

Fix #22

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@mattikus @stevvooe @dmcgowan PTAL

**Comment by mattikus** [comment]
LGTM. Thanks for taking a look!

File: zfs.go [hunk 1]
```diff
@@ -102,10 +103,16 @@ func cloneFilesystem(datasetName string, snapshot *zfs.Dataset) (*zfs.Dataset, e
 }
 
 func destroy(dataset *zfs.Dataset) error {
+	if strings.Contains(dataset.Name, "@") {
```
Comment (mattikus) [inline zfs.go]: Is it possible to have a dataset with an escaped `@`?

File: zfs.go [hunk 2]
```diff
@@ -244,9 +251,8 @@ func (z *snapshotter) Commit(ctx context.Context, name, key string, opts ...snap
 	err = t.Commit()
 	t = nil
 	if err != nil {
-		snapshotName := activeName + "@" + snapshotSuffix
 		if derr := destroySnapshot(snapshot); derr != nil {
-			log.G(ctx).WithError(derr).WithField("snapshotName", snapshotName).Error("failed to delete dataset")
+			log.G(ctx).WithError(derr).WithField("snapshotName", snapshot.Name).Error("failed to delete dataset")
```
Comment (mattikus) [inline zfs.go]: Is it worth calling this out as `failed to delete snapshot`?

File: zfs.go (hunk 1 above)
Comment (AkihiroSuda) [reply zfs.go]: removed this part. can be another PR.

File: zfs.go (hunk 2 above)
Comment (AkihiroSuda) [reply zfs.go]: removed this part. can be another PR.

**Comment by AkihiroSuda** [comment]
@fuweid PTAL?

**Comment by fuweid** [comment]
ping @AkihiroSuda sorry for the late reply. done

**Comment by AkihiroSuda** [comment]
thanks
